#!/bin/bash
#этот скрипт делает бэкап файла
filename=$1
homepath="/home/$USER"
trashpath=$homepath/.trash
trashlogpath=$homepath/trash.log
filepath=`pwd`/$filename
if ! [ -e $trashpath ]
then
  mkdir $trashpath
fi

linkname=`ls -l $trashpath | wc -l`

if ! [ -e $trashlogpath ]
then
  touch $trashlogpath
fi
if ! [ -e $filepath ] || [ $# -eq 0 ]
then
  echo "файл" $filename "не существует"
exit 1
fi
ln $filename $trashpath/$linkname
rm $filename
echo $filepath >> $trashlogpath
